/* Generated By:JavaCC: Do not edit this line. CSharpParserConstants.java */
package recoder.parser;

public interface CSharpParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 10;
  int FORMAL_COMMENT = 11;
  int MULTI_LINE_COMMENT = 12;
  int CSHARP_DOCCOMMENT = 23;
  int ABSTRACT = 24;
  int AS = 25;
  int BASE = 26;
  int BOOL = 27;
  int BREAK = 28;
  int BYTE = 29;
  int CASE = 30;
  int CATCH = 31;
  int CHAR = 32;
  int CHECKED = 33;
  int CLASS = 34;
  int CONST = 35;
  int CONTINUE = 36;
  int DECIMAL = 37;
  int _DEFAULT = 38;
  int DELEGATE = 39;
  int DO = 40;
  int DOUBLE = 41;
  int ELSE = 42;
  int ENUM = 43;
  int EVENT = 44;
  int EXPLICIT = 45;
  int EXTERN = 46;
  int FALSE = 47;
  int FINALLY = 48;
  int FIXED = 49;
  int FLOAT = 50;
  int FOR = 51;
  int FOREACH = 52;
  int GOTO = 53;
  int IF = 54;
  int IMPLICIT = 55;
  int IN = 56;
  int INT = 57;
  int INTERFACE = 58;
  int INTERNAL = 59;
  int IS = 60;
  int LOCK = 61;
  int LONG = 62;
  int NAMESPACE = 63;
  int NEW = 64;
  int NULL = 65;
  int OBJECT = 66;
  int OPERATOR = 67;
  int OUT = 68;
  int OVERRIDE = 69;
  int PARAMS = 70;
  int PRIVATE = 71;
  int PROTECTED = 72;
  int PUBLIC = 73;
  int READONLY = 74;
  int REF = 75;
  int RETURN = 76;
  int SBYTE = 77;
  int SEALED = 78;
  int SHORT = 79;
  int SIZEOF = 80;
  int STACKALLOC = 81;
  int STATIC = 82;
  int STRING = 83;
  int STRUCT = 84;
  int SWITCH = 85;
  int THIS = 86;
  int THROW = 87;
  int TRUE = 88;
  int TRY = 89;
  int TYPEOF = 90;
  int UINT = 91;
  int ULONG = 92;
  int UNCHECKED = 93;
  int UNSAFE = 94;
  int USHORT = 95;
  int USING = 96;
  int VIRTUAL = 97;
  int VOID = 98;
  int VOLATILE = 99;
  int WHILE = 100;
  int GET = 101;
  int SET = 102;
  int ADD = 103;
  int REMOVE = 104;
  int ASSEMBLY = 105;
  int FIELD = 106;
  int METHOD = 107;
  int MODULE = 108;
  int PARAM = 109;
  int PROPERTY = 110;
  int TYPE = 111;
  int INTEGER_LITERAL = 112;
  int DECIMAL_LITERAL = 113;
  int HEX_LITERAL = 114;
  int FLOATING_POINT_LITERAL = 115;
  int EXPONENT = 116;
  int CHARACTER_LITERAL = 117;
  int STRING_LITERAL = 118;
  int VERBATIM_STRING_LITERAL = 125;
  int IDENTIFIER = 126;
  int LETTER = 127;
  int DIGIT = 128;
  int LPAREN = 129;
  int RPAREN = 130;
  int LBRACE = 131;
  int RBRACE = 132;
  int LBRACKET = 133;
  int RBRACKET = 134;
  int SEMICOLON = 135;
  int COMMA = 136;
  int DOT = 137;
  int ASSIGN = 138;
  int GT = 139;
  int LT = 140;
  int BANG = 141;
  int TILDE = 142;
  int HOOK = 143;
  int COLON = 144;
  int EQ = 145;
  int LE = 146;
  int GE = 147;
  int NE = 148;
  int SC_OR = 149;
  int SC_AND = 150;
  int INCR = 151;
  int DECR = 152;
  int PLUS = 153;
  int MINUS = 154;
  int STAR = 155;
  int SLASH = 156;
  int BIT_AND = 157;
  int BIT_OR = 158;
  int XOR = 159;
  int REM = 160;
  int LSHIFT = 161;
  int RSIGNEDSHIFT = 162;
  int PLUSASSIGN = 163;
  int MINUSASSIGN = 164;
  int STARASSIGN = 165;
  int SLASHASSIGN = 166;
  int ANDASSIGN = 167;
  int ORASSIGN = 168;
  int XORASSIGN = 169;
  int REMASSIGN = 170;
  int LSHIFTASSIGN = 171;
  int RSIGNEDSHIFTASSIGN = 172;
  int ARROW = 173;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;
  int IN_CSHARP_DOCCOMMENT = 4;
  int IN_CSHARP_DOCCOMMENT_ENDOFLINE_1 = 5;
  int IN_CSHARP_DOCCOMMENT_ENDOFLINE_2 = 6;
  int CSHARP_DOCCOMMENT_ENDOFLINE = 7;
  int IN_VERBATIM_STRING_LITERAL = 8;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"///\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 13>",
    "<token of kind 14>",
    "\"\\r\\n\"",
    "\"///\"",
    "<token of kind 17>",
    "\"/\"",
    "\"//\"",
    "<token of kind 20>",
    "\"/\"",
    "\"//\"",
    "<CSHARP_DOCCOMMENT>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"false\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"null\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"get\"",
    "\"set\"",
    "\"add\"",
    "\"remove\"",
    "\"assembly\"",
    "\"field\"",
    "\"method\"",
    "\"module\"",
    "\"param\"",
    "\"property\"",
    "\"type\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"@\\\"\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\"\\\"\"",
    "<token of kind 124>",
    "\"\\\"\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"->\"",
  };

}
