/* Generated By:JavaCC: Do not edit this line. CSharpParserConstants.java */
package recoder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSharpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int REGION = 6;
  /** RegularExpression Id. */
  int ENDREGION = 7;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 12;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 13;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 14;
  /** RegularExpression Id. */
  int CSHARP_DOCCOMMENT = 25;
  /** RegularExpression Id. */
  int ABSTRACT = 26;
  /** RegularExpression Id. */
  int AS = 27;
  /** RegularExpression Id. */
  int BASE = 28;
  /** RegularExpression Id. */
  int BOOL = 29;
  /** RegularExpression Id. */
  int BREAK = 30;
  /** RegularExpression Id. */
  int BYTE = 31;
  /** RegularExpression Id. */
  int CASE = 32;
  /** RegularExpression Id. */
  int CATCH = 33;
  /** RegularExpression Id. */
  int CHAR = 34;
  /** RegularExpression Id. */
  int CHECKED = 35;
  /** RegularExpression Id. */
  int CLASS = 36;
  /** RegularExpression Id. */
  int CONST = 37;
  /** RegularExpression Id. */
  int CONTINUE = 38;
  /** RegularExpression Id. */
  int DECIMAL = 39;
  /** RegularExpression Id. */
  int _DEFAULT = 40;
  /** RegularExpression Id. */
  int DELEGATE = 41;
  /** RegularExpression Id. */
  int DO = 42;
  /** RegularExpression Id. */
  int DOUBLE = 43;
  /** RegularExpression Id. */
  int ELSE = 44;
  /** RegularExpression Id. */
  int ENUM = 45;
  /** RegularExpression Id. */
  int EVENT = 46;
  /** RegularExpression Id. */
  int EXPLICIT = 47;
  /** RegularExpression Id. */
  int EXTERN = 48;
  /** RegularExpression Id. */
  int FALSE = 49;
  /** RegularExpression Id. */
  int FINALLY = 50;
  /** RegularExpression Id. */
  int FIXED = 51;
  /** RegularExpression Id. */
  int FLOAT = 52;
  /** RegularExpression Id. */
  int FOR = 53;
  /** RegularExpression Id. */
  int FOREACH = 54;
  /** RegularExpression Id. */
  int GOTO = 55;
  /** RegularExpression Id. */
  int IF = 56;
  /** RegularExpression Id. */
  int IMPLICIT = 57;
  /** RegularExpression Id. */
  int IN = 58;
  /** RegularExpression Id. */
  int INT = 59;
  /** RegularExpression Id. */
  int INTERFACE = 60;
  /** RegularExpression Id. */
  int INTERNAL = 61;
  /** RegularExpression Id. */
  int IS = 62;
  /** RegularExpression Id. */
  int LOCK = 63;
  /** RegularExpression Id. */
  int LONG = 64;
  /** RegularExpression Id. */
  int NAMESPACE = 65;
  /** RegularExpression Id. */
  int NEW = 66;
  /** RegularExpression Id. */
  int NULL = 67;
  /** RegularExpression Id. */
  int OBJECT = 68;
  /** RegularExpression Id. */
  int OPERATOR = 69;
  /** RegularExpression Id. */
  int OUT = 70;
  /** RegularExpression Id. */
  int OVERRIDE = 71;
  /** RegularExpression Id. */
  int PARAMS = 72;
  /** RegularExpression Id. */
  int PARTIAL = 73;
  /** RegularExpression Id. */
  int PRIVATE = 74;
  /** RegularExpression Id. */
  int PROTECTED = 75;
  /** RegularExpression Id. */
  int PUBLIC = 76;
  /** RegularExpression Id. */
  int READONLY = 77;
  /** RegularExpression Id. */
  int REF = 78;
  /** RegularExpression Id. */
  int RETURN = 79;
  /** RegularExpression Id. */
  int SBYTE = 80;
  /** RegularExpression Id. */
  int SEALED = 81;
  /** RegularExpression Id. */
  int SHORT = 82;
  /** RegularExpression Id. */
  int SIZEOF = 83;
  /** RegularExpression Id. */
  int STACKALLOC = 84;
  /** RegularExpression Id. */
  int STATIC = 85;
  /** RegularExpression Id. */
  int STRING = 86;
  /** RegularExpression Id. */
  int STRUCT = 87;
  /** RegularExpression Id. */
  int SWITCH = 88;
  /** RegularExpression Id. */
  int THIS = 89;
  /** RegularExpression Id. */
  int THROW = 90;
  /** RegularExpression Id. */
  int TRUE = 91;
  /** RegularExpression Id. */
  int TRY = 92;
  /** RegularExpression Id. */
  int TYPEOF = 93;
  /** RegularExpression Id. */
  int UINT = 94;
  /** RegularExpression Id. */
  int ULONG = 95;
  /** RegularExpression Id. */
  int UNCHECKED = 96;
  /** RegularExpression Id. */
  int UNSAFE = 97;
  /** RegularExpression Id. */
  int USHORT = 98;
  /** RegularExpression Id. */
  int USING = 99;
  /** RegularExpression Id. */
  int VIRTUAL = 100;
  /** RegularExpression Id. */
  int VOID = 101;
  /** RegularExpression Id. */
  int VOLATILE = 102;
  /** RegularExpression Id. */
  int WHERE = 103;
  /** RegularExpression Id. */
  int WHILE = 104;
  /** RegularExpression Id. */
  int YIELD = 105;
  /** RegularExpression Id. */
  int GET = 106;
  /** RegularExpression Id. */
  int SET = 107;
  /** RegularExpression Id. */
  int ADD = 108;
  /** RegularExpression Id. */
  int REMOVE = 109;
  /** RegularExpression Id. */
  int ASSEMBLY = 110;
  /** RegularExpression Id. */
  int FIELD = 111;
  /** RegularExpression Id. */
  int METHOD = 112;
  /** RegularExpression Id. */
  int MODULE = 113;
  /** RegularExpression Id. */
  int PARAM = 114;
  /** RegularExpression Id. */
  int PROPERTY = 115;
  /** RegularExpression Id. */
  int TYPE = 116;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 117;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 118;
  /** RegularExpression Id. */
  int HEX_LITERAL = 119;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 120;
  /** RegularExpression Id. */
  int EXPONENT = 121;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 122;
  /** RegularExpression Id. */
  int STRING_LITERAL = 123;
  /** RegularExpression Id. */
  int VERBATIM_STRING_LITERAL = 130;
  /** RegularExpression Id. */
  int IDENTIFIER = 131;
  /** RegularExpression Id. */
  int LETTER = 132;
  /** RegularExpression Id. */
  int DIGIT = 133;
  /** RegularExpression Id. */
  int LPAREN = 134;
  /** RegularExpression Id. */
  int RPAREN = 135;
  /** RegularExpression Id. */
  int LBRACE = 136;
  /** RegularExpression Id. */
  int RBRACE = 137;
  /** RegularExpression Id. */
  int LBRACKET = 138;
  /** RegularExpression Id. */
  int RBRACKET = 139;
  /** RegularExpression Id. */
  int SEMICOLON = 140;
  /** RegularExpression Id. */
  int COMMA = 141;
  /** RegularExpression Id. */
  int DOT = 142;
  /** RegularExpression Id. */
  int ASSIGN = 143;
  /** RegularExpression Id. */
  int GT = 144;
  /** RegularExpression Id. */
  int LT = 145;
  /** RegularExpression Id. */
  int BANG = 146;
  /** RegularExpression Id. */
  int TILDE = 147;
  /** RegularExpression Id. */
  int HOOK = 148;
  /** RegularExpression Id. */
  int COLON = 149;
  /** RegularExpression Id. */
  int EQ = 150;
  /** RegularExpression Id. */
  int LE = 151;
  /** RegularExpression Id. */
  int GE = 152;
  /** RegularExpression Id. */
  int NE = 153;
  /** RegularExpression Id. */
  int SC_OR = 154;
  /** RegularExpression Id. */
  int SC_AND = 155;
  /** RegularExpression Id. */
  int INCR = 156;
  /** RegularExpression Id. */
  int DECR = 157;
  /** RegularExpression Id. */
  int PLUS = 158;
  /** RegularExpression Id. */
  int MINUS = 159;
  /** RegularExpression Id. */
  int STAR = 160;
  /** RegularExpression Id. */
  int SLASH = 161;
  /** RegularExpression Id. */
  int BIT_AND = 162;
  /** RegularExpression Id. */
  int BIT_OR = 163;
  /** RegularExpression Id. */
  int XOR = 164;
  /** RegularExpression Id. */
  int REM = 165;
  /** RegularExpression Id. */
  int LSHIFT = 166;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 167;
  /** RegularExpression Id. */
  int PLUSASSIGN = 168;
  /** RegularExpression Id. */
  int MINUSASSIGN = 169;
  /** RegularExpression Id. */
  int STARASSIGN = 170;
  /** RegularExpression Id. */
  int SLASHASSIGN = 171;
  /** RegularExpression Id. */
  int ANDASSIGN = 172;
  /** RegularExpression Id. */
  int ORASSIGN = 173;
  /** RegularExpression Id. */
  int XORASSIGN = 174;
  /** RegularExpression Id. */
  int REMASSIGN = 175;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 176;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 177;
  /** RegularExpression Id. */
  int ARROW = 178;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;
  /** Lexical state. */
  int IN_CSHARP_DOCCOMMENT = 4;
  /** Lexical state. */
  int IN_CSHARP_DOCCOMMENT_ENDOFLINE_1 = 5;
  /** Lexical state. */
  int IN_CSHARP_DOCCOMMENT_ENDOFLINE_2 = 6;
  /** Lexical state. */
  int CSHARP_DOCCOMMENT_ENDOFLINE = 7;
  /** Lexical state. */
  int IN_VERBATIM_STRING_LITERAL = 8;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<REGION>",
    "\"#endregion\"",
    "\"//\"",
    "<token of kind 9>",
    "\"/*\"",
    "\"///\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 15>",
    "<token of kind 16>",
    "\"\\r\\n\"",
    "\"///\"",
    "<token of kind 19>",
    "\"/\"",
    "\"//\"",
    "<token of kind 22>",
    "\"/\"",
    "\"//\"",
    "<CSHARP_DOCCOMMENT>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"false\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"null\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"partial\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"where\"",
    "\"while\"",
    "\"yield\"",
    "\"get\"",
    "\"set\"",
    "\"add\"",
    "\"remove\"",
    "\"assembly\"",
    "\"field\"",
    "\"method\"",
    "\"module\"",
    "\"param\"",
    "\"property\"",
    "\"type\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"@\\\"\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\"\\\"\"",
    "<token of kind 129>",
    "\"\\\"\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"->\"",
    "\"bool?\"",
    "\"char?\"",
    "\"sbyte?\"",
    "\"byte?\"",
    "\"short?\"",
    "\"ushort?\"",
    "\"int?\"",
    "\"uint?\"",
    "\"long?\"",
    "\"ulong?\"",
    "\"float?\"",
    "\"double?\"",
    "\"decimal?\"",
  };

}
